name       : glog
version    : 0.3.4
release    : 1
source     :
    - https://github.com/google/glog/archive/v0.3.4.tar.gz : ce99d58dce74458f7656a68935d7a0c048fa7b4626566a71b7f4e545920ceb10
license    : BSD-3-Clause
component  : programming
summary    : C++ implementation of the Google logging module
description: |
    C++ implementation of the Google logging module.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
